Repository breez/breez-sdk-liquid, pull requests merged in 2025-03, with the labels that each got.

#762 Recovery: Ensure wallet and chain service tips are within leeway
  lib/core/src/recover/recoverer.rs
  lib/core/src/send_swap.rs
  lib/core/src/test_utils/wallet.rs
  lib/core/src/wallet.rs
Labels: Testing

#765 Handle transition error on TimedOut
  lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
  lib/bindings/src/breez_sdk_liquid.udl
  lib/core/src/error.rs
  lib/core/src/frb_generated.rs
  lib/core/src/sdk.rs
  packages/dart/lib/src/error.dart
  packages/dart/lib/src/error.freezed.dart
  packages/dart/lib/src/frb_generated.dart
  packages/dart/lib/src/frb_generated.io.dart
  packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
Labels: Awaiting Integration

#771 Fix payment amount/fee for overpaid non-amountless chain swap
  lib/core/src/persist/mod.rs
Labels: Testing

#776 Fix LNURL drain and payment info
  lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
  lib/bindings/src/breez_sdk_liquid.udl
  lib/core/src/frb_generated.rs
  lib/core/src/model.rs
  lib/core/src/persist/mod.rs
  lib/core/src/sdk.rs
  lib/wasm/src/model.rs
  packages/dart/lib/src/frb_generated.dart
  packages/dart/lib/src/frb_generated.io.dart
  packages/dart/lib/src/model.dart
  packages/dart/lib/src/model.freezed.dart
  packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
  packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
  packages/react-native/ios/BreezSDKLiquidMapper.swift
  packages/react-native/src/index.ts
Labels: Testing, Awaiting Integration

#777 Notification Plugin: Dismiss replaceable notifications on service shutdown
  lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/ForegroundService.kt
Labels: Testing
